# Lab 2.2: Introduction to Pandas

**Student Name:** Yousaf Tahir  
**Registration Number:** 22JZELE0479  
**Course:** Machine Learning Lab  
**Supervisor:** Engr. Irshad Ullah  
**University:** UET Nowshera Campus  



## Learning Objectives
- Import Pandas and create DataFrames from dictionaries and arrays.
- Read tabular data from CSV files using Pandas.
- Inspect data using head, tail, info, describe, and shape.
- Practice indexing, filtering, grouping, and basic DataFrame operations used in ML data preparation.

## Section 1: Pandas Setup and DataFrame Creation
This section introduces Pandas and creates tabular data manually. This is the same structure used later when datasets are loaded for machine learning.

In [2]:
# !pip install pandas

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [3]:
import pandas

In [4]:
students = {
    'Name': ["Daniyal Basharat", "Yousaf Tahir", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [5]:
df = pandas.DataFrame(students)

In [6]:
df

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(students)

In [9]:
df

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [10]:
pd.__version__

'2.3.3'

## Saving to CSV and other extensions like excel

In [11]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [12]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [13]:
df.head()

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [14]:
df.head(3)

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19

In [15]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [16]:
df.tail()

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

In [17]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [18]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

               Name  Marks     Class  Age
0  Daniyal Basharat     80  1st Year   20
1      Yousaf Tahir     72  2nd Year   21
2     Muhammad Abid     77  1st Year   19
3      Shumail Khan     65  3rd Year   22
4         Qasim Ali     15  2nd Year   21

In [19]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1      Yousaf Tahir     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [20]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [21]:
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1      Yousaf Tahir     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [22]:
classData.drop(0, axis=0)

   Unnamed: 0           Name  Marks     Class  Age
1           1   Yousaf Tahir     72  2nd Year   21
2           2  Muhammad Abid     77  1st Year   19
3           3   Shumail Khan     65  3rd Year   22
4           4      Qasim Ali     15  2nd Year   21

In [23]:
classData

   Unnamed: 0              Name  Marks     Class  Age
0           0  Daniyal Basharat     80  1st Year   20
1           1      Yousaf Tahir     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

# Check the spelling

In [24]:
classData['Class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: Class, dtype: object

# Check the trail space

In [25]:
classData.columns = classData.columns.str.strip().str.lower()

In [26]:
classData['class']

0    1st Year
1    2nd Year
2    1st Year
3    3rd Year
4    2nd Year
Name: class, dtype: object

# Corrected Spelling

In [27]:
classData['name']

0    Daniyal Basharat
1        Yousaf Tahir
2       Muhammad Abid
3        Shumail Khan
4           Qasim Ali
Name: name, dtype: object

# Check the head space

In [28]:
classData['name']

0    Daniyal Basharat
1        Yousaf Tahir
2       Muhammad Abid
3        Shumail Khan
4           Qasim Ali
Name: name, dtype: object

In [29]:
type(classData['name'])

pandas.core.series.Series

In [30]:
classData['age']

0    20
1    21
2    19
3    22
4    21
Name: age, dtype: int64

classData['gpa'][0]

In [31]:
classData['age'][0]

np.int64(20)

In [32]:
classData['age'][0]=90

C:\Users\Yousaf Tahir\AppData\Local\Temp\ipykernel_19008\3711599208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['age'][0]=90

In [33]:
classData

   unnamed: 0              name  marks     class  age
0           0  Daniyal Basharat     80  1st Year   90
1           1      Yousaf Tahir     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year   21

In [34]:
classData['age'][4]

np.int64(21)

In [35]:
classData['age'][4]=5

C:\Users\Yousaf Tahir\AppData\Local\Temp\ipykernel_19008\2197085196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['age'][4]=5

In [36]:
classData["name"][4]

'Qasim Ali'

# Rename the column name

## Section 2: Reading and Inspecting Data
The following cells load data and inspect its rows, columns, summary, and structure. This step is necessary before cleaning or modeling any dataset.

In [37]:
classData.rename(columns={'age': 'AGE'})

   unnamed: 0              name  marks     class  AGE
0           0  Daniyal Basharat     80  1st Year   90
1           1      Yousaf Tahir     72  2nd Year   21
2           2     Muhammad Abid     77  1st Year   19
3           3      Shumail Khan     65  3rd Year   22
4           4         Qasim Ali     15  2nd Year    5

## Create Labels
With the index argument, you can name your own labels.

In [38]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

        unnamed: 0              name  marks     class  age
First            0  Daniyal Basharat     80  1st Year   90
Second           1      Yousaf Tahir     72  2nd Year   21
Third            2     Muhammad Abid     77  1st Year   19
Fourth           3      Shumail Khan     65  3rd Year   22
Fifth            4         Qasim Ali     15  2nd Year    5

# Asignment

In [39]:
classdata = classData.drop('unnamed: 0', axis=1)
classData

        unnamed: 0              name  marks     class  age
First            0  Daniyal Basharat     80  1st Year   90
Second           1      Yousaf Tahir     72  2nd Year   21
Third            2     Muhammad Abid     77  1st Year   19
Fourth           3      Shumail Khan     65  3rd Year   22
Fifth            4         Qasim Ali     15  2nd Year    5

# Inplace

In [40]:
classData.drop('unnamed: 0', axis=1, inplace = True)
classData

                    name  marks     class  age
First   Daniyal Basharat     80  1st Year   90
Second      Yousaf Tahir     72  2nd Year   21
Third      Muhammad Abid     77  1st Year   19
Fourth      Shumail Khan     65  3rd Year   22
Fifth          Qasim Ali     15  2nd Year    5

# Accessing the value in Dataframe

In [41]:
classData["name"]

First     Daniyal Basharat
Second        Yousaf Tahir
Third        Muhammad Abid
Fourth        Shumail Khan
Fifth            Qasim Ali
Name: name, dtype: object

In [42]:
classData["name"]["Fifth"]

'Qasim Ali'

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [43]:
classData['age']

First     90
Second    21
Third     19
Fourth    22
Fifth      5
Name: age, dtype: int64

In [44]:
type(classData['age'])

pandas.core.series.Series

In [45]:
classData

                    name  marks     class  age
First   Daniyal Basharat     80  1st Year   90
Second      Yousaf Tahir     72  2nd Year   21
Third      Muhammad Abid     77  1st Year   19
Fourth      Shumail Khan     65  3rd Year   22
Fifth          Qasim Ali     15  2nd Year    5

In [46]:
type(classData)

pandas.core.frame.DataFrame

In [47]:
import numpy as np

In [48]:
series1= pd.Series(np.random.rand())

In [49]:
series1

0    0.335722
dtype: float64

In [50]:
series1= pd.Series(np.random.rand(30))

In [51]:
series1

0     0.589319
1     0.619219
2     0.912343
3     0.965420
4     0.673272
5     0.687423
6     0.292357
7     0.517175
8     0.068120
9     0.489376
10    0.791431
11    0.394459
12    0.447798
13    0.168789
14    0.846219
15    0.197332
16    0.575101
17    0.941258
18    0.092797
19    0.046021
20    0.438677
21    0.643462
22    0.555341
23    0.048953
24    0.842255
25    0.738691
26    0.410803
27    0.621919
28    0.501580
29    0.244017
dtype: float64

In [52]:
type(series1)

pandas.core.series.Series

In [53]:
np.random.rand(3,4)

array([[0.82887269, 0.75345868, 0.82081119, 0.93167423],
       [0.90239708, 0.56007016, 0.53158091, 0.57248062],
       [0.87625712, 0.84624604, 0.23697185, 0.54838323]])

In [54]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [55]:
type(newDf)

pandas.core.frame.DataFrame

In [56]:
newDf.head(2)

          0         1         2         3         4
0  0.852333  0.911427  0.707793  0.255926  0.295086
1  0.493007  0.550698  0.364855  0.777431  0.974346

In [57]:
newDf.tail(2)

            0         1         2         3         4
328  0.216642  0.787520  0.108219  0.516880  0.047711
329  0.657438  0.830894  0.604932  0.162833  0.404739

In [58]:
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [59]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.498236    0.491939    0.509227    0.500725    0.510972
std      0.285196    0.283987    0.297734    0.291977    0.287960
min      0.000385    0.002436    0.000288    0.001081    0.000348
25%      0.249236    0.248266    0.267723    0.239695    0.292256
50%      0.502360    0.491518    0.503821    0.490232    0.508292
75%      0.746123    0.725408    0.789473    0.758375    0.752191
max      0.993645    0.997473    0.996750    0.995072    0.999492

In [60]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# Change the value inside the dataframe

In [61]:
newDf[0][0]= 10000.0

C:\Users\Yousaf Tahir\AppData\Local\Temp\ipykernel_19008\1615845312.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDf[0][0]= 10000.0

In [62]:
newDf

                0         1         2         3         4
0    10000.000000  0.911427  0.707793  0.255926  0.295086
1        0.493007  0.550698  0.364855  0.777431  0.974346
2        0.365780  0.131906  0.790104  0.631851  0.014425
3        0.142638  0.331590  0.196686  0.747585  0.616075
4        0.417112  0.195816  0.458032  0.387625  0.000530
..            ...       ...       ...       ...       ...
325      0.498084  0.367662  0.307217  0.683186  0.128883
326      0.210385  0.126511  0.079453  0.041907  0.306616
327      0.193488  0.400793  0.380254  0.691804  0.656592
328      0.216642  0.787520  0.108219  0.516880  0.047711
329      0.657438  0.830894  0.604932  0.162833  0.404739

[330 rows x 5 columns]

In [63]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.911427  0.707793  0.255926  0.295086
1      0.493007  0.550698  0.364855  0.777431  0.974346
2      0.365780  0.131906  0.790104  0.631851  0.014425
3      0.142638  0.331590  0.196686  0.747585  0.616075
4      0.417112  0.195816  0.458032  0.387625  0.000530

# Transpose

In [64]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,10000.000000,0.493007,0.365780,0.142638,0.417112,0.001206,0.511365,0.683898,0.910489,0.429035,...,0.298646,0.887095,0.637168,0.262662,0.553654,0.498084,0.210385,0.193488,0.216642,0.657438
1,0.911427,0.550698,0.131906,0.331590,0.195816,0.606269,0.036684,0.846690,0.577604,0.150372,...,0.530642,0.708039,0.418674,0.573301,0.258079,0.367662,0.126511,0.400793,0.787520,0.830894
2,0.707793,0.364855,0.790104,0.196686,0.458032,0.063358,0.672989,0.875489,0.376880,0.063221,...,0.004325,0.373321,0.307610,0.125952,0.382960,0.307217,0.079453,0.380254,0.108219,0.604932
3,0.255926,0.777431,0.631851,0.747585,0.387625,0.942340,0.927634,0.235921,0.651138,0.465141,...,0.921622,0.931447,0.004930,0.770780,0.293889,0.683186,0.041907,0.691804,0.516880,0.162833
4,0.295086,0.974346,0.014425,0.616075,0.000530,0.527244,0.006781,0.871284,0.519973,0.414797,...,0.950341,0.866741,0.329197,0.527007,0.756642,0.128883,0.306616,0.656592,0.047711,0.404739

# Sorting

In [65]:
newDf.sort_index(axis=0)

                0         1         2         3         4
0    10000.000000  0.911427  0.707793  0.255926  0.295086
1        0.493007  0.550698  0.364855  0.777431  0.974346
2        0.365780  0.131906  0.790104  0.631851  0.014425
3        0.142638  0.331590  0.196686  0.747585  0.616075
4        0.417112  0.195816  0.458032  0.387625  0.000530
..            ...       ...       ...       ...       ...
325      0.498084  0.367662  0.307217  0.683186  0.128883
326      0.210385  0.126511  0.079453  0.041907  0.306616
327      0.193488  0.400793  0.380254  0.691804  0.656592
328      0.216642  0.787520  0.108219  0.516880  0.047711
329      0.657438  0.830894  0.604932  0.162833  0.404739

[330 rows x 5 columns]

In [66]:
newDf.sort_index(axis=0, ascending=False)

                0         1         2         3         4
329      0.657438  0.830894  0.604932  0.162833  0.404739
328      0.216642  0.787520  0.108219  0.516880  0.047711
327      0.193488  0.400793  0.380254  0.691804  0.656592
326      0.210385  0.126511  0.079453  0.041907  0.306616
325      0.498084  0.367662  0.307217  0.683186  0.128883
..            ...       ...       ...       ...       ...
4        0.417112  0.195816  0.458032  0.387625  0.000530
3        0.142638  0.331590  0.196686  0.747585  0.616075
2        0.365780  0.131906  0.790104  0.631851  0.014425
1        0.493007  0.550698  0.364855  0.777431  0.974346
0    10000.000000  0.911427  0.707793  0.255926  0.295086

[330 rows x 5 columns]

In [67]:
newDf.sort_index(axis=1)

                0         1         2         3         4
0    10000.000000  0.911427  0.707793  0.255926  0.295086
1        0.493007  0.550698  0.364855  0.777431  0.974346
2        0.365780  0.131906  0.790104  0.631851  0.014425
3        0.142638  0.331590  0.196686  0.747585  0.616075
4        0.417112  0.195816  0.458032  0.387625  0.000530
..            ...       ...       ...       ...       ...
325      0.498084  0.367662  0.307217  0.683186  0.128883
326      0.210385  0.126511  0.079453  0.041907  0.306616
327      0.193488  0.400793  0.380254  0.691804  0.656592
328      0.216642  0.787520  0.108219  0.516880  0.047711
329      0.657438  0.830894  0.604932  0.162833  0.404739

[330 rows x 5 columns]

In [68]:
newDf.sort_index(axis=1, ascending=False)

            4         3         2         1             0
0    0.295086  0.255926  0.707793  0.911427  10000.000000
1    0.974346  0.777431  0.364855  0.550698      0.493007
2    0.014425  0.631851  0.790104  0.131906      0.365780
3    0.616075  0.747585  0.196686  0.331590      0.142638
4    0.000530  0.387625  0.458032  0.195816      0.417112
..        ...       ...       ...       ...           ...
325  0.128883  0.683186  0.307217  0.367662      0.498084
326  0.306616  0.041907  0.079453  0.126511      0.210385
327  0.656592  0.691804  0.380254  0.400793      0.193488
328  0.047711  0.516880  0.108219  0.787520      0.216642
329  0.404739  0.162833  0.604932  0.830894      0.657438

[330 rows x 5 columns]

In [69]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.911427  0.707793  0.255926  0.295086
1      0.493007  0.550698  0.364855  0.777431  0.974346
2      0.365780  0.131906  0.790104  0.631851  0.014425
3      0.142638  0.331590  0.196686  0.747585  0.616075
4      0.417112  0.195816  0.458032  0.387625  0.000530

In [70]:
newDf[0][1]

np.float64(0.4930071817745908)

In [71]:
type(newDf[0])

pandas.core.series.Series

In [72]:
newDf

                0         1         2         3         4
0    10000.000000  0.911427  0.707793  0.255926  0.295086
1        0.493007  0.550698  0.364855  0.777431  0.974346
2        0.365780  0.131906  0.790104  0.631851  0.014425
3        0.142638  0.331590  0.196686  0.747585  0.616075
4        0.417112  0.195816  0.458032  0.387625  0.000530
..            ...       ...       ...       ...       ...
325      0.498084  0.367662  0.307217  0.683186  0.128883
326      0.210385  0.126511  0.079453  0.041907  0.306616
327      0.193488  0.400793  0.380254  0.691804  0.656592
328      0.216642  0.787520  0.108219  0.516880  0.047711
329      0.657438  0.830894  0.604932  0.162833  0.404739

[330 rows x 5 columns]

## view

In [73]:
newDfView=newDf

In [74]:
newDfView

                0         1         2         3         4
0    10000.000000  0.911427  0.707793  0.255926  0.295086
1        0.493007  0.550698  0.364855  0.777431  0.974346
2        0.365780  0.131906  0.790104  0.631851  0.014425
3        0.142638  0.331590  0.196686  0.747585  0.616075
4        0.417112  0.195816  0.458032  0.387625  0.000530
..            ...       ...       ...       ...       ...
325      0.498084  0.367662  0.307217  0.683186  0.128883
326      0.210385  0.126511  0.079453  0.041907  0.306616
327      0.193488  0.400793  0.380254  0.691804  0.656592
328      0.216642  0.787520  0.108219  0.516880  0.047711
329      0.657438  0.830894  0.604932  0.162833  0.404739

[330 rows x 5 columns]

In [75]:
newDfView[0][0]=765

C:\Users\Yousaf Tahir\AppData\Local\Temp\ipykernel_19008\4063526219.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfView[0][0]=765

In [76]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.911427  0.707793  0.255926  0.295086
1    0.493007  0.550698  0.364855  0.777431  0.974346
2    0.365780  0.131906  0.790104  0.631851  0.014425
3    0.142638  0.331590  0.196686  0.747585  0.616075
4    0.417112  0.195816  0.458032  0.387625  0.000530

## Section 3: Data Selection, Filtering, and Grouping
These operations help extract useful information from data and are commonly used during feature selection and exploratory data analysis.

In [77]:
newDfView.head()

            0         1         2         3         4
0  765.000000  0.911427  0.707793  0.255926  0.295086
1    0.493007  0.550698  0.364855  0.777431  0.974346
2    0.365780  0.131906  0.790104  0.631851  0.014425
3    0.142638  0.331590  0.196686  0.747585  0.616075
4    0.417112  0.195816  0.458032  0.387625  0.000530

In [78]:
newDfCopy=newDf.copy()

In [79]:
newDfCopy[0][0]=656

C:\Users\Yousaf Tahir\AppData\Local\Temp\ipykernel_19008\2532441962.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfCopy[0][0]=656

In [80]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.911427  0.707793  0.255926  0.295086
1    0.493007  0.550698  0.364855  0.777431  0.974346
2    0.365780  0.131906  0.790104  0.631851  0.014425
3    0.142638  0.331590  0.196686  0.747585  0.616075
4    0.417112  0.195816  0.458032  0.387625  0.000530

In [81]:
newDfCopy.head()

            0         1         2         3         4
0  656.000000  0.911427  0.707793  0.255926  0.295086
1    0.493007  0.550698  0.364855  0.777431  0.974346
2    0.365780  0.131906  0.790104  0.631851  0.014425
3    0.142638  0.331590  0.196686  0.747585  0.616075
4    0.417112  0.195816  0.458032  0.387625  0.000530

In [82]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [83]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      object
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

In [84]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [85]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [86]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [87]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [88]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [89]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:3, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76
3   Hina     89

In [90]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [91]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [92]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [93]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [94]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [95]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [96]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [97]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [98]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [99]:
df.drop(['Age'], axis=1, inplace=True)

In [100]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [101]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [102]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [103]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [104]:
df.reset_index(drop=True, inplace=True)

In [105]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [106]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [107]:
df = pd.DataFrame(data)

In [108]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [109]:
df.groupby('Company')

##### You can save this object as a new variable:

In [110]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [111]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [112]:
df.groupby('Company').std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [113]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [114]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [115]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [116]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [117]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

## Final Conclusion
In this lab, Pandas was used for tabular data handling. These skills are important for dataset collection, inspection, cleaning, and preparation before model training.